### ISSUE TITLE
Invalid record(s) found

### ISSUE THREAD

**Issue by ThomasVermes** [uwctri/Recalculate#2]
Hi Adam,
I found this issue:
If the record's first instrument is not saved, the module will not find the record.
Nevertheless, for there record there is some calc fields to be corrected.
I don't remind where, but it is not the first time that this (first instrument not saved) cause me problems.

![image](https://user-images.githubusercontent.com/75424115/182549134-79a504a9-7699-4f33-8044-774f430d3565.png)
![image](https://user-images.githubusercontent.com/75424115/182549148-b92c1b57-3376-405c-90cd-ea0d5cd3272f.png)
![image](https://user-images.githubusercontent.com/75424115/182549175-fd014dca-4f59-4615-a5b0-fb9dab3769e3.png)

**Comment by aanunez** [comment]
Hey Thomas,

I'll be fixing and releasing an update for this issue later in the week.

**Comment by aanunez** [comment]
Vanderbilt accepted the update for this a few days ago. Could you confirm the issue has been resolved after updating?

**Comment by aanunez** [comment]
@ThomasVermes Could you confirm that this issue was resolved in your environment?

**Comment by ThomasVermes** [comment]
Dear Adam,

it seems to work =)

**Comment by ThomasVermes** [comment]
Dear Adam,

it looks like it works!

Thank you very much again =)
Best
Thomas
