### ISSUE TITLE
Schedule list going back to page 1

### ISSUE THREAD

**Issue by ThomasVermes** [uwctri/Recalculate#6]
![image](https://github.com/uwctri/Recalculate/assets/75424115/8dca1019-70cf-4ea1-96f9-a7fa8dd6b11a)

after clicking on "Schedule to run" my long list of scheduled recalculation is displayed.
I have 13 pages. If I click on the last page (or just another page X), the page is correctly open.
A strange behaviour after some short time of inactivity on that page X (i.e. going on another tab on the browser for 1 minute or less and going back to redcap or just staying on that page X) makes the list going back to page 1.
best
Thomas

**Comment by aanunez** [comment]
This is likely the data being refreshed to the screen and the page value being reset when all the data is updated. We should stash the page and try to set the value after a refresh.

**Comment by aanunez** [comment]
[Just resolved](https://github.com/uwctri/Recalculate/commit/8db6057c77db90a1732460a3b6cc1616d45f3cb0). Planning to do a release soon.
