### ISSUE TITLE
citation file .cff

### ISSUE THREAD

**Issue by ThomasVermes** [uwctri/Recalculate#7]
Dear Adam,

what about to add a citation file (.cff)?

https://citation-file-format.github.io/#:~:text=cff%20files%20are%20plain%20text,to%20correctly%20cite%20their%20software.
https://redcap.vanderbilt.edu/community/post.php?id=118384

I would like to write a technical paper on a data collection project and I would like to cite your EM!

lg
Thomas

**Comment by aanunez** [comment]
Hi Thomas,

I've added the cff file. Thanks for asking! It references the most recent release, but if you'd prefer to cite some version you used specifically feel free to edit the commit, version, and date of release.
